/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AnalyzeUsernameRouteImport } from './routes/analyze.$username'
import { Route as ApiSyncUserRouteImport } from './routes/api/sync-user'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DrillUsernameRouteImport } from './routes/drill.$username'
import { Route as EndgamesUsernameRouteImport } from './routes/endgames.$username'
import { Route as OpeningsUsernameRouteImport } from './routes/openings.$username'
import { Route as PositionsUsernameRouteImport } from './routes/positions.$username'
import { Route as PuzzlesUsernameRouteImport } from './routes/puzzles.$username'
import { Route as ResultsUsernameRouteImport } from './routes/results.$username'
import { Route as ReviewIndexRouteImport } from './routes/review.index'
import { Route as ReviewUsernameRouteImport } from './routes/review.$username'
import { Route as RoadmapUsernameRouteImport } from './routes/roadmap.$username'
import { Route as StrategyUsernameRouteImport } from './routes/strategy.$username'
import { Route as TrainerUsernameRouteImport } from './routes/trainer.$username'
import { Route as ResultsUsernameIndexRouteImport } from './routes/results.$username.index'
import { Route as ResultsUsernameEndgamesRouteImport } from './routes/results.$username.endgames'
import { Route as ResultsUsernameOpeningsRouteImport } from './routes/results.$username.openings'
import { Route as ResultsUsernameStrategyRouteImport } from './routes/results.$username.strategy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeUsernameRoute = AnalyzeUsernameRouteImport.update({
  id: '/analyze/$username',
  path: '/analyze/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncUserRoute = ApiSyncUserRouteImport.update({
  id: '/api/sync-user',
  path: '/api/sync-user',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillUsernameRoute = DrillUsernameRouteImport.update({
  id: '/drill/$username',
  path: '/drill/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const EndgamesUsernameRoute = EndgamesUsernameRouteImport.update({
  id: '/endgames/$username',
  path: '/endgames/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const OpeningsUsernameRoute = OpeningsUsernameRouteImport.update({
  id: '/openings/$username',
  path: '/openings/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsUsernameRoute = PositionsUsernameRouteImport.update({
  id: '/positions/$username',
  path: '/positions/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesUsernameRoute = PuzzlesUsernameRouteImport.update({
  id: '/puzzles/$username',
  path: '/puzzles/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsUsernameRoute = ResultsUsernameRouteImport.update({
  id: '/results/$username',
  path: '/results/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReviewRoute,
} as any)
const ReviewUsernameRoute = ReviewUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => ReviewRoute,
} as any)
const RoadmapUsernameRoute = RoadmapUsernameRouteImport.update({
  id: '/roadmap/$username',
  path: '/roadmap/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyUsernameRoute = StrategyUsernameRouteImport.update({
  id: '/strategy/$username',
  path: '/strategy/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerUsernameRoute = TrainerUsernameRouteImport.update({
  id: '/trainer/$username',
  path: '/trainer/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsUsernameIndexRoute = ResultsUsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResultsUsernameRoute,
} as any)
const ResultsUsernameEndgamesRoute = ResultsUsernameEndgamesRouteImport.update({
  id: '/endgames',
  path: '/endgames',
  getParentRoute: () => ResultsUsernameRoute,
} as any)
const ResultsUsernameOpeningsRoute = ResultsUsernameOpeningsRouteImport.update({
  id: '/openings',
  path: '/openings',
  getParentRoute: () => ResultsUsernameRoute,
} as any)
const ResultsUsernameStrategyRoute = ResultsUsernameStrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => ResultsUsernameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/preview': typeof PreviewRoute
  '/review': typeof ReviewRouteWithChildren
  '/signup': typeof SignupRoute
  '/analyze/$username': typeof AnalyzeUsernameRoute
  '/api/sync-user': typeof ApiSyncUserRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/drill/$username': typeof DrillUsernameRoute
  '/endgames/$username': typeof EndgamesUsernameRoute
  '/openings/$username': typeof OpeningsUsernameRoute
  '/positions/$username': typeof PositionsUsernameRoute
  '/puzzles/$username': typeof PuzzlesUsernameRoute
  '/results/$username': typeof ResultsUsernameRouteWithChildren
  '/review/$username': typeof ReviewUsernameRoute
  '/roadmap/$username': typeof RoadmapUsernameRoute
  '/strategy/$username': typeof StrategyUsernameRoute
  '/trainer/$username': typeof TrainerUsernameRoute
  '/review/': typeof ReviewIndexRoute
  '/results/$username/endgames': typeof ResultsUsernameEndgamesRoute
  '/results/$username/openings': typeof ResultsUsernameOpeningsRoute
  '/results/$username/strategy': typeof ResultsUsernameStrategyRoute
  '/results/$username/': typeof ResultsUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/preview': typeof PreviewRoute
  '/signup': typeof SignupRoute
  '/analyze/$username': typeof AnalyzeUsernameRoute
  '/api/sync-user': typeof ApiSyncUserRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/drill/$username': typeof DrillUsernameRoute
  '/endgames/$username': typeof EndgamesUsernameRoute
  '/openings/$username': typeof OpeningsUsernameRoute
  '/positions/$username': typeof PositionsUsernameRoute
  '/puzzles/$username': typeof PuzzlesUsernameRoute
  '/review/$username': typeof ReviewUsernameRoute
  '/roadmap/$username': typeof RoadmapUsernameRoute
  '/strategy/$username': typeof StrategyUsernameRoute
  '/trainer/$username': typeof TrainerUsernameRoute
  '/review': typeof ReviewIndexRoute
  '/results/$username/endgames': typeof ResultsUsernameEndgamesRoute
  '/results/$username/openings': typeof ResultsUsernameOpeningsRoute
  '/results/$username/strategy': typeof ResultsUsernameStrategyRoute
  '/results/$username': typeof ResultsUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/preview': typeof PreviewRoute
  '/review': typeof ReviewRouteWithChildren
  '/signup': typeof SignupRoute
  '/analyze/$username': typeof AnalyzeUsernameRoute
  '/api/sync-user': typeof ApiSyncUserRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/drill/$username': typeof DrillUsernameRoute
  '/endgames/$username': typeof EndgamesUsernameRoute
  '/openings/$username': typeof OpeningsUsernameRoute
  '/positions/$username': typeof PositionsUsernameRoute
  '/puzzles/$username': typeof PuzzlesUsernameRoute
  '/results/$username': typeof ResultsUsernameRouteWithChildren
  '/review/$username': typeof ReviewUsernameRoute
  '/roadmap/$username': typeof RoadmapUsernameRoute
  '/strategy/$username': typeof StrategyUsernameRoute
  '/trainer/$username': typeof TrainerUsernameRoute
  '/review/': typeof ReviewIndexRoute
  '/results/$username/endgames': typeof ResultsUsernameEndgamesRoute
  '/results/$username/openings': typeof ResultsUsernameOpeningsRoute
  '/results/$username/strategy': typeof ResultsUsernameStrategyRoute
  '/results/$username/': typeof ResultsUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/preview'
    | '/review'
    | '/signup'
    | '/analyze/$username'
    | '/api/sync-user'
    | '/auth/callback'
    | '/drill/$username'
    | '/endgames/$username'
    | '/openings/$username'
    | '/positions/$username'
    | '/puzzles/$username'
    | '/results/$username'
    | '/review/$username'
    | '/roadmap/$username'
    | '/strategy/$username'
    | '/trainer/$username'
    | '/review/'
    | '/results/$username/endgames'
    | '/results/$username/openings'
    | '/results/$username/strategy'
    | '/results/$username/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/preview'
    | '/signup'
    | '/analyze/$username'
    | '/api/sync-user'
    | '/auth/callback'
    | '/drill/$username'
    | '/endgames/$username'
    | '/openings/$username'
    | '/positions/$username'
    | '/puzzles/$username'
    | '/review/$username'
    | '/roadmap/$username'
    | '/strategy/$username'
    | '/trainer/$username'
    | '/review'
    | '/results/$username/endgames'
    | '/results/$username/openings'
    | '/results/$username/strategy'
    | '/results/$username'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/preview'
    | '/review'
    | '/signup'
    | '/analyze/$username'
    | '/api/sync-user'
    | '/auth/callback'
    | '/drill/$username'
    | '/endgames/$username'
    | '/openings/$username'
    | '/positions/$username'
    | '/puzzles/$username'
    | '/results/$username'
    | '/review/$username'
    | '/roadmap/$username'
    | '/strategy/$username'
    | '/trainer/$username'
    | '/review/'
    | '/results/$username/endgames'
    | '/results/$username/openings'
    | '/results/$username/strategy'
    | '/results/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PreviewRoute: typeof PreviewRoute
  ReviewRoute: typeof ReviewRouteWithChildren
  SignupRoute: typeof SignupRoute
  AnalyzeUsernameRoute: typeof AnalyzeUsernameRoute
  ApiSyncUserRoute: typeof ApiSyncUserRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  DrillUsernameRoute: typeof DrillUsernameRoute
  EndgamesUsernameRoute: typeof EndgamesUsernameRoute
  OpeningsUsernameRoute: typeof OpeningsUsernameRoute
  PositionsUsernameRoute: typeof PositionsUsernameRoute
  PuzzlesUsernameRoute: typeof PuzzlesUsernameRoute
  ResultsUsernameRoute: typeof ResultsUsernameRouteWithChildren
  RoadmapUsernameRoute: typeof RoadmapUsernameRoute
  StrategyUsernameRoute: typeof StrategyUsernameRoute
  TrainerUsernameRoute: typeof TrainerUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze/$username': {
      id: '/analyze/$username'
      path: '/analyze/$username'
      fullPath: '/analyze/$username'
      preLoaderRoute: typeof AnalyzeUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync-user': {
      id: '/api/sync-user'
      path: '/api/sync-user'
      fullPath: '/api/sync-user'
      preLoaderRoute: typeof ApiSyncUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill/$username': {
      id: '/drill/$username'
      path: '/drill/$username'
      fullPath: '/drill/$username'
      preLoaderRoute: typeof DrillUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endgames/$username': {
      id: '/endgames/$username'
      path: '/endgames/$username'
      fullPath: '/endgames/$username'
      preLoaderRoute: typeof EndgamesUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openings/$username': {
      id: '/openings/$username'
      path: '/openings/$username'
      fullPath: '/openings/$username'
      preLoaderRoute: typeof OpeningsUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions/$username': {
      id: '/positions/$username'
      path: '/positions/$username'
      fullPath: '/positions/$username'
      preLoaderRoute: typeof PositionsUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles/$username': {
      id: '/puzzles/$username'
      path: '/puzzles/$username'
      fullPath: '/puzzles/$username'
      preLoaderRoute: typeof PuzzlesUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$username': {
      id: '/results/$username'
      path: '/results/$username'
      fullPath: '/results/$username'
      preLoaderRoute: typeof ResultsUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/': {
      id: '/review/'
      path: '/'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/review/$username': {
      id: '/review/$username'
      path: '/$username'
      fullPath: '/review/$username'
      preLoaderRoute: typeof ReviewUsernameRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/roadmap/$username': {
      id: '/roadmap/$username'
      path: '/roadmap/$username'
      fullPath: '/roadmap/$username'
      preLoaderRoute: typeof RoadmapUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy/$username': {
      id: '/strategy/$username'
      path: '/strategy/$username'
      fullPath: '/strategy/$username'
      preLoaderRoute: typeof StrategyUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/$username': {
      id: '/trainer/$username'
      path: '/trainer/$username'
      fullPath: '/trainer/$username'
      preLoaderRoute: typeof TrainerUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$username/': {
      id: '/results/$username/'
      path: '/'
      fullPath: '/results/$username/'
      preLoaderRoute: typeof ResultsUsernameIndexRouteImport
      parentRoute: typeof ResultsUsernameRoute
    }
    '/results/$username/endgames': {
      id: '/results/$username/endgames'
      path: '/endgames'
      fullPath: '/results/$username/endgames'
      preLoaderRoute: typeof ResultsUsernameEndgamesRouteImport
      parentRoute: typeof ResultsUsernameRoute
    }
    '/results/$username/openings': {
      id: '/results/$username/openings'
      path: '/openings'
      fullPath: '/results/$username/openings'
      preLoaderRoute: typeof ResultsUsernameOpeningsRouteImport
      parentRoute: typeof ResultsUsernameRoute
    }
    '/results/$username/strategy': {
      id: '/results/$username/strategy'
      path: '/strategy'
      fullPath: '/results/$username/strategy'
      preLoaderRoute: typeof ResultsUsernameStrategyRouteImport
      parentRoute: typeof ResultsUsernameRoute
    }
  }
}

interface ReviewRouteChildren {
  ReviewUsernameRoute: typeof ReviewUsernameRoute
  ReviewIndexRoute: typeof ReviewIndexRoute
}

const ReviewRouteChildren: ReviewRouteChildren = {
  ReviewUsernameRoute: ReviewUsernameRoute,
  ReviewIndexRoute: ReviewIndexRoute,
}

const ReviewRouteWithChildren =
  ReviewRoute._addFileChildren(ReviewRouteChildren)

interface ResultsUsernameRouteChildren {
  ResultsUsernameEndgamesRoute: typeof ResultsUsernameEndgamesRoute
  ResultsUsernameOpeningsRoute: typeof ResultsUsernameOpeningsRoute
  ResultsUsernameStrategyRoute: typeof ResultsUsernameStrategyRoute
  ResultsUsernameIndexRoute: typeof ResultsUsernameIndexRoute
}

const ResultsUsernameRouteChildren: ResultsUsernameRouteChildren = {
  ResultsUsernameEndgamesRoute: ResultsUsernameEndgamesRoute,
  ResultsUsernameOpeningsRoute: ResultsUsernameOpeningsRoute,
  ResultsUsernameStrategyRoute: ResultsUsernameStrategyRoute,
  ResultsUsernameIndexRoute: ResultsUsernameIndexRoute,
}

const ResultsUsernameRouteWithChildren = ResultsUsernameRoute._addFileChildren(
  ResultsUsernameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PreviewRoute: PreviewRoute,
  ReviewRoute: ReviewRouteWithChildren,
  SignupRoute: SignupRoute,
  AnalyzeUsernameRoute: AnalyzeUsernameRoute,
  ApiSyncUserRoute: ApiSyncUserRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  DrillUsernameRoute: DrillUsernameRoute,
  EndgamesUsernameRoute: EndgamesUsernameRoute,
  OpeningsUsernameRoute: OpeningsUsernameRoute,
  PositionsUsernameRoute: PositionsUsernameRoute,
  PuzzlesUsernameRoute: PuzzlesUsernameRoute,
  ResultsUsernameRoute: ResultsUsernameRouteWithChildren,
  RoadmapUsernameRoute: RoadmapUsernameRoute,
  StrategyUsernameRoute: StrategyUsernameRoute,
  TrainerUsernameRoute: TrainerUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
