/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AnalyzeUsernameRouteImport } from './routes/analyze.$username'
import { Route as ApiSyncUserRouteImport } from './routes/api/sync-user'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DrillUsernameRouteImport } from './routes/drill.$username'
import { Route as PositionsUsernameRouteImport } from './routes/positions.$username'
import { Route as ResultsUsernameRouteImport } from './routes/results.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeUsernameRoute = AnalyzeUsernameRouteImport.update({
  id: '/analyze/$username',
  path: '/analyze/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncUserRoute = ApiSyncUserRouteImport.update({
  id: '/api/sync-user',
  path: '/api/sync-user',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillUsernameRoute = DrillUsernameRouteImport.update({
  id: '/drill/$username',
  path: '/drill/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsUsernameRoute = PositionsUsernameRouteImport.update({
  id: '/positions/$username',
  path: '/positions/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsUsernameRoute = ResultsUsernameRouteImport.update({
  id: '/results/$username',
  path: '/results/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/preview': typeof PreviewRoute
  '/signup': typeof SignupRoute
  '/analyze/$username': typeof AnalyzeUsernameRoute
  '/api/sync-user': typeof ApiSyncUserRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/drill/$username': typeof DrillUsernameRoute
  '/positions/$username': typeof PositionsUsernameRoute
  '/results/$username': typeof ResultsUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/preview': typeof PreviewRoute
  '/signup': typeof SignupRoute
  '/analyze/$username': typeof AnalyzeUsernameRoute
  '/api/sync-user': typeof ApiSyncUserRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/drill/$username': typeof DrillUsernameRoute
  '/positions/$username': typeof PositionsUsernameRoute
  '/results/$username': typeof ResultsUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/preview': typeof PreviewRoute
  '/signup': typeof SignupRoute
  '/analyze/$username': typeof AnalyzeUsernameRoute
  '/api/sync-user': typeof ApiSyncUserRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/drill/$username': typeof DrillUsernameRoute
  '/positions/$username': typeof PositionsUsernameRoute
  '/results/$username': typeof ResultsUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/preview'
    | '/signup'
    | '/analyze/$username'
    | '/api/sync-user'
    | '/auth/callback'
    | '/drill/$username'
    | '/positions/$username'
    | '/results/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/preview'
    | '/signup'
    | '/analyze/$username'
    | '/api/sync-user'
    | '/auth/callback'
    | '/drill/$username'
    | '/positions/$username'
    | '/results/$username'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/preview'
    | '/signup'
    | '/analyze/$username'
    | '/api/sync-user'
    | '/auth/callback'
    | '/drill/$username'
    | '/positions/$username'
    | '/results/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PreviewRoute: typeof PreviewRoute
  SignupRoute: typeof SignupRoute
  AnalyzeUsernameRoute: typeof AnalyzeUsernameRoute
  ApiSyncUserRoute: typeof ApiSyncUserRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  DrillUsernameRoute: typeof DrillUsernameRoute
  PositionsUsernameRoute: typeof PositionsUsernameRoute
  ResultsUsernameRoute: typeof ResultsUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze/$username': {
      id: '/analyze/$username'
      path: '/analyze/$username'
      fullPath: '/analyze/$username'
      preLoaderRoute: typeof AnalyzeUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync-user': {
      id: '/api/sync-user'
      path: '/api/sync-user'
      fullPath: '/api/sync-user'
      preLoaderRoute: typeof ApiSyncUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill/$username': {
      id: '/drill/$username'
      path: '/drill/$username'
      fullPath: '/drill/$username'
      preLoaderRoute: typeof DrillUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions/$username': {
      id: '/positions/$username'
      path: '/positions/$username'
      fullPath: '/positions/$username'
      preLoaderRoute: typeof PositionsUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$username': {
      id: '/results/$username'
      path: '/results/$username'
      fullPath: '/results/$username'
      preLoaderRoute: typeof ResultsUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PreviewRoute: PreviewRoute,
  SignupRoute: SignupRoute,
  AnalyzeUsernameRoute: AnalyzeUsernameRoute,
  ApiSyncUserRoute: ApiSyncUserRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  DrillUsernameRoute: DrillUsernameRoute,
  PositionsUsernameRoute: PositionsUsernameRoute,
  ResultsUsernameRoute: ResultsUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
